# 1. Неймспейс (на всякий случай, если он еще не создан)
apiVersion: v1
kind: Namespace
metadata:
  name: production
---
# 2. MongoDB - База данных (минимальная конфигурация для работы)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: production
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4
        ports:
        - containerPort: 27017
        command:
          - mongod
          - "--oplogSize"
          - "128"
          - "--replSet"
          - "rs0"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: production
spec:
  ports:
  - port: 27017
  selector:
    app: mongodb
---
# 3. Приложение Rocket.Chat
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocket-chat
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocket-chat
  template:
    metadata:
      labels:
        app: rocket-chat
    spec:
      containers:
      - name: rocket-chat
        # ВАЖНО: Тег :latest будет заменен на :SHA_COMMIT вашим пайплайном
        image: cr.yandex/crpkbvrrnvvh2cn7ta1f/rocket-chat:latest 
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          value: "mongodb://mongodb:27017/rocketchat?replicaSet=rs0"
        - name: MONGO_OPLOG_URL
          value: "mongodb://mongodb:27017/local?replicaSet=rs0"
        - name: ROOT_URL
          value: "http://rocket-chat.production.svc.cluster.local"
        - name: PORT
          value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: rocket-chat
  namespace: production
spec:
  type: LoadBalancer # Это создаст внешний IP в Yandex Cloud, чтобы вы могли зайти в чат
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: rocket-chat
