name: Hybrid CI/CD RocketChat

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: [self-hosted, local-dev]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          clean: true
          submodules: false

      - name: Login to Registry
        run: |
          echo "${{ secrets.YC_OAUTH_TOKEN }}" | docker login --username oauth --password-stdin cr.yandex

      - name: Build and Push
        run: |
          docker build -t cr.yandex/${{ secrets.YC_REGISTRY_ID }}/rocket-chat:${{ github.sha }} .
          docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/rocket-chat:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: [self-hosted, production-broker]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Deploy to K8s
        run: |
          kubectl apply -f k8s/production-deployment.yaml
          kubectl set image deployment/rocket-chat rocket-chat=cr.yandex/${{ secrets.YC_REGISTRY_ID }}/rocket-chat:${{ github.sha }} -n production
