name: Hybrid CI/CD RocketChat

on:
  push:
    branches:
      - develop  # Запускаем при пуше в develop

jobs:
  build-and-push:
    runs-on: [self-hosted, local-dev] # Ваша VM1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          clean: true
          submodules: false

      - name: Login to Registry
        run: echo "${{ secrets.YC_SA_KEY_FILE }}" | docker login --username json_key --password-stdin cr.yandex

      - name: Build and Push
        run: |
          docker build -t cr.yandex/${{ secrets.YC_REGISTRY_ID }}/rocket-chat:${{ github.sha }} .
          docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/rocket-chat:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: [self-hosted, production-broker] # Ваш Раннер в K8s
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to K8s
        run: |
          kubectl apply -f k8s/production-deployment.yaml
          kubectl set image deployment/rocket-chat rocket-chat=cr.yandex/${{ secrets.YC_REGISTRY_ID }}/rocket-chat:${{ github.sha }} -n production
